// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package data

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Plan struct {
	ID         int32            `json:"id"`
	PlanName   pgtype.Text      `json:"plan_name"`
	PlanAmount pgtype.Int4      `json:"plan_amount"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID         int32            `json:"id"`
	Email      pgtype.Text      `json:"email"`
	FirstName  pgtype.Text      `json:"first_name"`
	LastName   pgtype.Text      `json:"last_name"`
	Password   pgtype.Text      `json:"password"`
	UserActive pgtype.Int4      `json:"user_active"`
	IsAdmin    pgtype.Int4      `json:"is_admin"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type UserPlan struct {
	ID        int32            `json:"id"`
	UserID    pgtype.Int4      `json:"user_id"`
	PlanID    pgtype.Int4      `json:"plan_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
