// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package data

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	DeleteUser(ctx context.Context, id int32) error
	DeleteUserByID(ctx context.Context, id int32) error
	GetAllUsers(ctx context.Context, arg GetAllUsersParams) ([]User, error)
	GetOneUser(ctx context.Context, id int32) (User, error)
	GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
